language: python
python: 
  - "3.7"
install: 
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pip3 install travis-wait-improved
  - python -c "import nltk; nltk.download('wordnet'); nltk.download('averaged_perceptron_tagger')"
script:
  - travis-wait-improved --timeout 40m pytest
  
